### ISSUE TITLE
Spacing between \sbreak and \subsection

### ISSUE THREAD

**Issue by rjl20** [rjl20/hpmor#1]
There's too much space between section breaks and subsection headers. Reduce it, ideally without resorting to inline \vspace hacks.

**Comment by rrthomas** [comment]
Since this issue has already been solved with inline \vspace hacks, the issue now is really to remove that hack.

**Comment by rrthomas** [comment]
Fixed this as best I could (i.e. not properly, I couldn't work out how to make \sbreak space better with \subsection) in my commit rrthomas/hpmor@d2dbc07568783be129cd1cf69f441d705eea1e05
