### ISSUE TITLE
Are you still interested in maintaining this?

### ISSUE THREAD

**Issue by rrthomas** [rjl20/hpmor#11]
My PR #10 has grown: I've undertaken quite a bit of tidy-up of the LaTeX, and also intend to add many "Brit-fixes" to the text that I noted while reading the book.

So, @rjl20, if you're still interested in maintaining the project, I'm happy to make the work into a series of PRs that can be discussed and applied as you see fit; for the moment I'm just pushing everything to my fork, so the PR is now rather mis-described!

**Comment by rjl20** [comment]
Honestly, I'm probably not going to be doing much maintenance of this in the foreseeable future -- I've sent you a collaboration request on this fork, or it'd be easy to point the link on the web site to your fork instead. Thanks for all the work you've done on this!

**Comment by rrthomas** [comment]
You're welcome! I'll happily collaborate on your repo.
