### ISSUE TITLE
New Chapters are missing foreshadowing epigraphs

### ISSUE THREAD

**Issue by JoshuaOSHickman** [rjl20/hpmor#2]
Notably, the HJPEV and The Methods of Rationality subbook doesn't open with the silver-fraction-of-a-line bit.

**Comment by rjl20** [comment]
I went back and forth on how to handle the epigraphs. Ultimately, I thought it was confusing to have epigraphs in the book form when some of them referred to something within the chapter they headed and some didn't pay off for hundreds of pages. And there were only 18 of them, all at the beginning. If they'd been spread out to indicate the start of a new plot arc or something, I would have left them where they were, but as it was they felt like an early idea that had been abandoned. Leaving just the first one in might make some kind of structural sense, but ... boy, it really doesn't fit the tone of the first few chapters.

They've been moved to an appendix at the back of the full PDF in my fork; you're welcome to re-insert them into the chapters in your own fork, if you want.

**Comment by domenic** [comment]
Upon re-reading all the book-style PDFs, I honestly think just inserting the very first chapter's epigraph would be a good touch. It is very different in tone, but that's actually kind of nice ... it gives you a sense that while this book starts out kind of silly, there's something more sinister coming.

Also ... as an aside, was that epigraph _really_ written as it is now, back when chapter 1 was released!? That's some serious foreshadowing.
