### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by entorb** [rjl20/hpmor#29]
There is a [repo of a German translation](https://github.com/elkablo/hpmor) of the first book, foreked from this repo. I am considering converting the [existing translations for the remaining 5 books](https://www.fanfiktion.de/s/60044849000ccc541aef297e/1/Ubersetzung-Harry-Potter-und-die-Methoden-des-rationalen-Denkens-Harry-Potter-and-the-methods-of-rationality) into LaTeX. What do you think, should the translation be merged into your repo, or shall they stay separate?

**Comment by rrthomas** [comment]
Exciting news!

There are pros and cons. I've worked on a large LaTeX translation in the past, and it was essentially two sets of parallel files (they were kept in the same repo, but no need). My German is not good enough to make decisions about a translation, or collaborate in.

The main advantages I see would be the possibility to have a unified design (is that good?) and also to feed errata (i.e. not just translation problems) in both directions.

It would be possible to have a unified design by separating out the design elements into a separate repo that is included as a submodule in each book, and to solve the coordination problem with a mailing list (although those seem to be out of fashion these days!).

One other option that occurs to me is to keep the translation as a permanent fork, with the possibility to merge design changes, and the natural loose collaboration that comes with having a fork.

What do you think?

**Comment by entorb** [comment]
After some hands-on in chapter 22, I decided that the typesetting is too much work for now, so I postponed the idea of converting the German html into latex code.

I think your last proposal of a permanent fork (as done in the repo above) might be the easiest strategy, as the benefit of having multiple languages in one might not justify the effort.

**Comment by rrthomas** [comment]
OK! Maybe a task to do a bit at a time over several months/years?

I agree; after thinking about it, a permanent fork feels like the most workable system to me too.
