### ISSUE TITLE
harmonizing hyphens

### ISSUE THREAD

**Issue by entorb** [rjl20/hpmor#32]
I used this [old tool of mine](https://entorb.net/TypoNukeTool/), for checking the usage of hyphens. It found quite some variations, like "time-travel" vs. "time travel", see [attachment](https://github.com/rjl20/hpmor/files/7744017/hpmor-hyphens.txt). Any native-speaker interested in harmonizing those?

**Comment by rrthomas** [comment]
Is your tool open source/free software? Sounds interesting.

I think I can look at this issue.

**Comment by rrthomas** [comment]
Some of these will probably be false positives: in particular, my style is to hyphenate when I use a noun phrase as an adjective, and not when I use it as a noun: "time-travel sickness" vs "the perils of time travel".

**Comment by entorb** [comment]
So far I have not published the code of that ond perl tool, will check how ugly the code is, and that reconsider ;-).

Yes, quite some are be false positives for sure.

**Comment by entorb** [comment]
source of my tool is now [published](https://github.com/entorb/typonuketool), but be aware it is quite old and ugly
