### ISSUE TITLE
Add 6 separate PDFs and add volume title into complete PDF

### ISSUE THREAD

**Issue by entorb** [rjl20/hpmor#34]
I suggest adding the creation of the 6 part/volume pdfs to the release pipeline. Currently, people browsing to the release page do not know that these printable volumes exist.

Furthermore, I suggest adding this 6-volume structure into the complete PDF, for example using 
\part{Harry James Potter-Evans-Verres and the Methods of Rationality}
\part{Harry James Potter-Evans-Verres and the Professor's Games}
...
or similar.
So that in the table of contents and at the start of each part/volume the volume title is displayed. 
In the e-book version I already did so.

When I first read the book, I did not realize this substructure and upon realization I very much liked it.

**Comment by rrthomas** [comment]
I'm not sure I agree; I think this is just a division of convenience for physical printing. Do we have some evidence that this is what the author intended?

**Comment by entorb** [comment]
I have no clue who came up with the titles for the 6 volumes. As I first encountered them on hpmor.com I assumed it was the author's intention. Nevertheless, I very much like them and would therefore prefer to display them in the complete pdf as well.

**Comment by rrthomas** [comment]
If the titles are just nice extras for a physical division for a book that is impractical as a single volume, I don't think they have any special claim to be added to the single-volume edition (whether e-book or PDF).

**Comment by rjl20** [comment]
The split points for arcs/books and their titles were actually suggested by Yudkowsky, for what it's worth: https://www.reddit.com/r/HPMOR/comments/2z116j/chapter_122/cpeqcdh/

**Comment by rrthomas** [comment]
Thanks, @rjl20. @entorb, I look forward to your patch!
