### ISSUE TITLE
error on latexmk on 008 and 009

### ISSUE THREAD

**Issue by yeKcim** [rjl20/hpmor#38]
```
latexmk -norc -e '$chapter=008' -r ../latexmkrc -g "hpmor-chapter-008"

Latexmk: Stopping because executing following code from command line
    $chapter=008
gave an error:
    Illegal octal digit '8' at (eval 9) line 1, at end of line
```

Book is ok, chapter 1 to 7 are ok, 10 or 13 are ok too. For Chapters 8 and 9 I have this error on my computer.

**Comment by rrthomas** [comment]
The instructions could be clearer. In this case, you should write:

`latexmk -norc -e '$chapter=8' -r ../latexmkrc -g hpmor-chapter-008`

That is why the instructions say `N` the first time and `NNN` the second: the first time a number is needed, and the second, the full filename. The number must be in decimal, and in Perl (the language in which `latexmk` is written), numbers starting with `0` are assumed to be octal.

I'll clarify the instructions.
