### ISSUE TITLE
Wrong quotation mark

### ISSUE THREAD

**Issue by apt1002** [rjl20/hpmor#45]
”So it was you the Sorting Hat was
warning me about!” has a closing quotation mark at the beginning.

**Comment by apt1002** [comment]
”What I said was true. I did discover one of
Severus’s secrets, and I did do some blackmail. But Severus wasn’t the
only person involved.” also has a closing quotation mark at the beginning.

**Comment by rrthomas** [comment]
These are already fixed, sorry. I'll make a new release.
