### ISSUE TITLE
Parsel &nbsp; becomes &nbssp; in html

### ISSUE THREAD

**Issue by aleksandar-j** [rjl20/hpmor#50]
When converting parsel, convert_parsel function in ebook/1_latex2html.py replaces each 's' with 'ss' which breaks \&nbsp; within it.

**Comment by aleksandar-j** [comment]
I am not familiar with the full code here but a simple replace("&nbssp;", "&nbsp;") add works and produces the right output. Though perhaps someone else might find a more elegant solution. #51

**Comment by aleksandar-j** [comment]
Forgot to mention that this happens once in chapter 58, though you can just search for "&nbssp;" to easily find this.

**Comment by rrthomas** [comment]
Fixed by #51.
