### ISSUE TITLE
Missing line break in chapter 13

### ISSUE THREAD

**Issue by fefrei** [rjl20/hpmor#54]
From the source of chapter 13:

```tex
Then he pulled out the drawer.
\begin{align*}\intertext{\scshape \centering
Opportunities to do good are everywhere\\
but darkness is where the light needs to be}
\hbox{\scshape Cost of question: }&\hbox{\scshape 1 point}\\
\hbox{\scshape Current points: }&\hbox{74}\\[1.5ex]
\multicolumn{2}{c}{\scshape Nice underwear}\\
\multicolumn{2}{c}{\scshape Did your mother pick them out?}\\
\end{align*}
```

This renders fine in the PDF – but in the MOBI version (as rendered by my Kindle), “darkness is where light needs to be Cost of question” ends up in one line. I guess the converter script isn't fully aware of what `\intertext` is doing?

**Comment by rrthomas** [comment]
@entorb, can you take a look at this, please?

**Comment by rrthomas** [comment]
Should be fixed by #55.

**Comment by fefrei** [comment]
Wohoo! 🎉

Thank you for your work – reading HPMOR on an e-book reader is really nice ❤️

**Comment by rrthomas** [comment]
I've made a new release (1.1.10) with this and other recent minor fixes.

**Comment by entorb** [comment]
There might be more such minor issues in the ebook, feel free to report them too.

**Comment by fefrei** [comment]
Will do! I'll be compiling a list on this read-through so I don't bother you with lots of mini issues, though :-)

**Comment by entorb** [comment]
Thanks!

**Comment by rrthomas** [comment]
Thanks both @fefrei and @entorb for your efforts. It's great to fix even minor irritations for the reader, and fantastic that we make sure that all formats work as well as we can.

**Comment by fefrei** [comment]
I'm done with my read-through. The results are #81, a minor PR with missing spaces, and #82, a list of minor issues with the MOBI version.

Thanks, again, for your work, @entorb and @rrthomas – I absolutely appreciate the efforts you make to make this masterpiece shine in all forms!

**Comment by rrthomas** [comment]
Thanks for your painstaking work, @fefrei.
