### ISSUE TITLE
Parseltounge em dashes are left as ---

### ISSUE THREAD

**Issue by domenic** [rjl20/hpmor#6]
I only noticed this in book 5 since I re-downloaded it after the new font, but I imagine that it's in all the books now.

Two places I actually noted down as I went were page 161 ("intent---who") and page 204 ("would you not---"). Hopefully that's enough to go on.

**Comment by rjl20** [comment]
Good catch; I'd forgotten to enable ligatures for fonts other than the main text. I'm rebuilding the PDFs now. It was the case for the first, harder-to-read, font I'd picked too, but it was harder to see in that.

**Comment by rjl20** [comment]
Fixed in 60719e2d825e1621ac774e7d5f0c4075c245d033. Thanks!
