### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by hmh** [rjl20/hpmor#8]
Please consider adding some sort of revision numbering note somewhere in the resulting book (it can be discreet), so that one can relate which version of the source was used to produce a PDF or EPUB, etc.

The last page looks like a good place to do it, since you lack the library index and publishing information page at the start of the book.

**Comment by rjl20** [comment]
Good call. I made an abortive attempt at that earlier, but ran into issues trying to get git version information included automatically. I've abandoned that approach in favor of the much simpler method of having LaTeX include the current time and date at build time on the colophon page. I should have that committed soon.

**Comment by rjl20** [comment]
Fixed in 0c10d2e8b6bd68e88fd2fc6e6b233140917e7314.

**Comment by rjl20** [comment]
I realize belatedly that having a timestamp in the finished product isn't quite as handy as having the commit hash of the source used to compile it. Unfortunately, getting the hash info was just not working for me when I tried it earlier. I may give it another try at some point, but for now, timestamp is what I can do.
