### ISSUE TITLE
Relative to TL2014, datetime2.sty and tracklang.sty should be added

### ISSUE THREAD

**Issue by rrthomas** [rjl20/hpmor#9]
README.md doesn't specify what the expected baseline for building hpmor is; it would seem fair to assume _at most_ the most recent release of TeXLive. As far as I can see, both the above-mentioned packages have been added since then.

README.md says somewhat misleadingly that the pkg directory contains packages that "might be tricky to find". Of the packages in that directory, two are easy-peasy (microtype 2.5a, as shipped in TL 2014, and lettrine 1.64, which is _older_ than the 1.70 shipped in TL 2014) and one is well-nigh impossible (ucntn.sty I cannot find in TeXLive, CTAN or anywhere else except in this project).

Would you accept a patch that a) specifies what the baseline requirements are for building hpmor; b) removes microtype & lettrine, assuming that they are part of the baseline; and c) adds the two above-mentioned packages?

(Both datetime2 and tracklang _are_ available in TeXLive 2015, so once that is released and considered widely-available enough to become the baseline, if you think suitable, then those two packages could be removed again.)

**Comment by rjl20** [comment]
I would love a patch like that; thanks!

**Comment by rrthomas** [comment]
Great, I'll make one. Don't let the quite probable delay before its appearance let you think I've forgotten: I'm horribly busy just now.

**Comment by rjl20** [comment]
No worries; so am I (hence the 11 day delay after your offer).

**Comment by rrthomas** [comment]
Finally got around to making that PR. The advantage of waiting two years is that I think it's now reasonable to require TeXLive 2015, which means I've been able to remove the pkg directory altogether.
